### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by mdaliyan** [CodepadME/laravel-tricks#90]
Has any one considered making a feed for this website?

I haven't done any project on Laravel yet, but my first project on laravel I think adding rss feed wouldn't be so hard. 

I hate to say something and don't do it. any suggestions?

**Comment by mdaomega** [comment]
Ok, I saw the code. there are rss and atom feeds included inside. but I can't figure it out why it throws:

> Whoops, looks like something went wrong.

**Comment by agmckee** [comment]
@mdaliyan Illuminate\View\Environment was renamed Illuminate\View\Factory some time ago. That is likely the cause of this error.

**Comment by agmckee** [comment]
@mdaliyan Illuminate\View\Environment was renamed Illuminate\View\Factory some time ago. That is likely the cause of the error.

**Comment by agmckee** [comment]
@mdaliyan Illuminate\View\Environment was renamed Illuminate\View\Factory some time ago. That is likely the cause of the error.

**Comment by agmckee** [comment]
@mdaliyan Illuminate\View\Environment was renamed Illuminate\View\Factory some time ago. That is likely the cause of the error.
