### ISSUE TITLE
unable to deploy this project on shared hosting

### ISSUE THREAD

**Issue by sahil1572** [CodepadME/laravel-tricks#91]
is there any way to use this project without Redis 
as my godaddy shared hosting does not provide redis server 
getting errror 

Predis \ Connection \ ConnectionException
Connection refused [tcp://127.0.0.1:6379]

**Comment by sahil1572** [comment]
Got it working after setting up local caching on instead redis

**Comment by msurguy** [comment]
@sahil1572 great! Thanks for getting back here and reporting how you fixed the issue!
